# title: Jason M. Setiadi
# logo: /images/potrait.jpg
# description: Data Scientist/Machine Learning Engineer
# show_downloads: 
# google_analytics:
# theme: jekyll-theme-minimal

# Site settings
title: Jason M. Setiadi
email: 
description: Data Scientist/Machine Learning Engineer
baseurl: ""
url: "http://jasonmsetiadi.github.io"
# twitter_username: jasonmsetiadi
github_username:  jasonmsetiadi

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge