title: Jason M. Setiadi
logo: /images/potrait.jpg
description: University of Minnesota Twin Cities: Bachelor of Science in Statistical Science with minors in Computer Science and Mathematics
show_downloads: 
google_analytics:
theme: jekyll-theme-minimal
